/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
package br.univali.ttoproject.compiler.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int BLOCK_COMMENT = 6;
  /** RegularExpression Id. */
  int PROGRAM = 9;
  /** RegularExpression Id. */
  int DEFINE = 10;
  /** RegularExpression Id. */
  int NOT = 11;
  /** RegularExpression Id. */
  int VARIABLE = 12;
  /** RegularExpression Id. */
  int IS = 13;
  /** RegularExpression Id. */
  int NATURAL = 14;
  /** RegularExpression Id. */
  int REAL = 15;
  /** RegularExpression Id. */
  int CHAR = 16;
  /** RegularExpression Id. */
  int BOOLEAN = 17;
  /** RegularExpression Id. */
  int EXECUTE = 18;
  /** RegularExpression Id. */
  int SET = 19;
  /** RegularExpression Id. */
  int TO = 20;
  /** RegularExpression Id. */
  int GET = 21;
  /** RegularExpression Id. */
  int PUT = 22;
  /** RegularExpression Id. */
  int VERIFY = 23;
  /** RegularExpression Id. */
  int TRUE = 24;
  /** RegularExpression Id. */
  int FALSE = 25;
  /** RegularExpression Id. */
  int LOOP = 26;
  /** RegularExpression Id. */
  int WHILE = 27;
  /** RegularExpression Id. */
  int DO = 28;
  /** RegularExpression Id. */
  int LBRACE = 29;
  /** RegularExpression Id. */
  int RBRACE = 30;
  /** RegularExpression Id. */
  int PARENTHESESL = 31;
  /** RegularExpression Id. */
  int PARANTHESESR = 32;
  /** RegularExpression Id. */
  int DOT = 33;
  /** RegularExpression Id. */
  int COMMA = 34;
  /** RegularExpression Id. */
  int PLUS = 35;
  /** RegularExpression Id. */
  int MINUS = 36;
  /** RegularExpression Id. */
  int POWER = 37;
  /** RegularExpression Id. */
  int MULTIPLICATION = 38;
  /** RegularExpression Id. */
  int DIVISION = 39;
  /** RegularExpression Id. */
  int INTEGER_DIVISION = 40;
  /** RegularExpression Id. */
  int REST = 41;
  /** RegularExpression Id. */
  int EQUAL = 42;
  /** RegularExpression Id. */
  int DIFFERENT = 43;
  /** RegularExpression Id. */
  int SMALLER = 44;
  /** RegularExpression Id. */
  int LARGER = 45;
  /** RegularExpression Id. */
  int SMALLER_EQUAL = 46;
  /** RegularExpression Id. */
  int LARGER_EQUAL = 47;
  /** RegularExpression Id. */
  int AND = 48;
  /** RegularExpression Id. */
  int OR = 49;
  /** RegularExpression Id. */
  int NOT_SYMBOL = 50;
  /** RegularExpression Id. */
  int IDENTIFIER = 51;
  /** RegularExpression Id. */
  int LETTER = 52;
  /** RegularExpression Id. */
  int UNSIGNED = 53;
  /** RegularExpression Id. */
  int SIGNED = 54;
  /** RegularExpression Id. */
  int REAL_UNSIGNED = 55;
  /** RegularExpression Id. */
  int REAL_SIGNED = 56;
  /** RegularExpression Id. */
  int STRING = 57;
  /** RegularExpression Id. */
  int UNKNOWN = 58;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int BLOCK_COMMENT_STATE = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "\"/*\"",
    "\"*/\"",
    "<token of kind 8>",
    "\"program\"",
    "\"define\"",
    "\"not\"",
    "\"variable\"",
    "\"is\"",
    "\"natural\"",
    "\"real\"",
    "\"char\"",
    "\"boolean\"",
    "\"execute\"",
    "\"set\"",
    "\"to\"",
    "\"get\"",
    "\"put\"",
    "\"verify\"",
    "\"true\"",
    "\"false\"",
    "\"loop\"",
    "\"while\"",
    "\"do\"",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
    "\".\"",
    "\",\"",
    "\"+\"",
    "\"-\"",
    "\"**\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"%%\"",
    "\"==\"",
    "\"!=\"",
    "\"<\"",
    "\">\"",
    "\"<=\"",
    "\">=\"",
    "\"&\"",
    "\"|\"",
    "\"!\"",
    "<IDENTIFIER>",
    "<LETTER>",
    "<UNSIGNED>",
    "<SIGNED>",
    "<REAL_UNSIGNED>",
    "<REAL_SIGNED>",
    "<STRING>",
    "<UNKNOWN>",
  };

}
